#!/usr/bin/env bash
#
# A wizard - walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library - delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets these two at the top of the stages section.
TOTAL_STAGES=0
TOTAL_MINUTES=0

_STAGE_INDEX=0
_MINUTES_ELAPSED=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear - wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" - opening frame: what this wizard does and how long it takes.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages · about %s minutes%s\n\n' \
    "$DIM" "$TOTAL_STAGES" "$TOTAL_MINUTES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" <minutes> - clear the screen, then announce a stage and show
# progress + time remaining. Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  local remaining=$((TOTAL_MINUTES - _MINUTES_ELAPSED))
  (( remaining < 0 )) && remaining=0
  _MINUTES_ELAPSED=$((_MINUTES_ELAPSED + ${2:-0}))
  printf '\n%s%s▸ Stage %s/%s · %s%s  %s(~%s min left)%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET" "$DIM" "$remaining" "$RESET"
}

# say "..." - a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." - a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL - open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser, visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, visit it manually: $url"
}

# pause "msg" - wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" - y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY - current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" - read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" - like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE - upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE - set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name, gh not ready; set it later"
}

# set_var NAME VALUE - set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish - clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES - author this section. One stage() per step the human takes.
# Replace the example below. Set the two totals to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=12
# Sum of the per-stage estimates below. Most of it is Stage 8 waiting on the
# GitHub Actions docker build, which is why this is not a 20-minute job.
TOTAL_MINUTES=116

# ==========================================================================
# Constants. Every name below is DERIVED FROM THE REPO, not invented here.
# If you change one of these, change the workflow that reads it too.
# ==========================================================================

REPO_ROOT=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." && pwd)

# gh refuses to guess when a clone has more than one remote, and this clone has
# both `origin` (Raghavgali) and `upstream` (MLOpsGroup9). GH_REPO pins every gh
# call in this script, including the ones inside the library helpers, to the fork
# we actually deploy from.
GH_REPO_SLUG="Raghavgali/FrontShiftAI"
export GH_REPO="$GH_REPO_SLUG"

# gcloud must never block on a prompt in the middle of a stage.
export CLOUDSDK_CORE_DISABLE_PROMPTS=1

# From .github/workflows/deploy-backend.yml (env: block).
GCP_REGION="us-central1"
CLOUD_RUN_SERVICE="frontshiftai-backend"
ARTIFACT_REPOSITORY="frontshiftai-backend"

# Secret Manager entries named by deploy-backend.yml `--set-secrets`. The deploy
# fails outright if any one of these does not exist, so all five are mandatory
# even when a key is a placeholder.
BACKEND_SECRETS="GROQ_API_KEY BRAVE_API_KEY JWT_SECRET_KEY INCEPTION_API_KEY DATABASE_URL"

# From backend/db/seed.py. These are NOT in the workflow's --set-secrets yet,
# which is the blocker Stage 6 explains.
SEED_SECRET_NAMES="SEED_SUPER_ADMIN_PASSWORD SEED_ADMIN_PASSWORD SEED_USER_PASSWORD SEED_DEMO_PASSWORD"

# Workflow file names, used with `gh workflow run`.
BACKEND_WORKFLOW="deploy-backend.yml"
PAGES_WORKFLOW="deploy-pages.yml"

# Fixed by the GitHub Pages config already on the repo.
LANDING_URL="https://raghavgali.github.io/FrontShiftAI/"
CHAT_APP_URL="https://raghavgali.github.io/FrontShiftAI/app/"

# Workload Identity Federation resource ids.
WIF_POOL="github-actions-pool"
WIF_PROVIDER="github-provider"
DEPLOY_SA_ID="github-actions-deploy"

# From voice_pipeline/modal_deploy.py: modal.App("frontshiftai-voice-agent")
# and the three modal.Secret.from_name() calls.
MODAL_APP="frontshiftai-voice-agent"
MODAL_SECRET_LIVEKIT="livekit-credentials"
MODAL_SECRET_PROVIDERS="voice-agent-providers"
MODAL_SECRET_BACKEND="voice-agent-backend"

# Burned project ids. The old shared-group project and its deploy twin must not
# be reused: their JWT secret and service-account JWT are both in git history.
FORBIDDEN_PROJECT_IDS="frontshiftai frontshiftai-deploy"

# APIs. run/artifactregistry/secretmanager/iamcredentials are what the deploy
# touches directly. iam + sts are needed for Workload Identity token exchange,
# cloudresourcemanager for the IAM policy bindings, and compute because Cloud
# Run's default runtime identity IS the Compute Engine default service account:
# without that API the account does not exist and `gcloud run deploy` has no
# identity to attach.
REQUIRED_APIS="run.googleapis.com artifactregistry.googleapis.com secretmanager.googleapis.com iamcredentials.googleapis.com iam.googleapis.com sts.googleapis.com cloudresourcemanager.googleapis.com compute.googleapis.com"

# Stage markers, in order. Named rather than numbered so inserting a stage
# later does not invalidate a half-finished state file.
STAGE_ORDER="PREFLIGHT GCP_PROJECT WIF NEON APP_SECRETS SEED_SECRETS GITHUB_CONFIG BACKEND_DEPLOY PAGES_DEPLOY VOICE_KEYS MODAL_DEPLOY VERIFY"

# Progress lives here, not in .env: this file records which stages are done and
# the non-secret values later stages need. It is gitignored. No secret value is
# ever written to it, only markers saying a secret was created.
ENV_FILE="$REPO_ROOT/deployment/.go_live.state"

# ==========================================================================
# Wizard-specific helpers. The library above is generic; these add the four
# things this particular job needs: dry-run, resumability, a safe path for
# secret material, and honest labelling of anything unverified.
# ==========================================================================

DRY_RUN=0
FORCE_ALL=0
FORCE_STAGES=""
NONINTERACTIVE=0
[[ -t 0 ]] || NONINTERACTIVE=1

RESUMED=()
BLOCKERS=()

usage() {
  cat <<'USAGE'
Usage: deployment/go_live.sh [options]

Walks you through taking FrontShiftAI live under your own accounts: a new GCP
project, Workload Identity Federation, a Neon Postgres database, Secret Manager
entries, GitHub repo secrets and variables, the first Cloud Run deploy, the
GitHub Pages build, and the Modal voice agent.

Options:
  --dry-run             Print every mutating command instead of running it.
                        Read-only probes still run, so the plan is accurate.
  --force               Re-run every stage even if the state file says it is done.
  --force-stage NAME    Re-run one stage. Repeatable. Valid names:
                        PREFLIGHT GCP_PROJECT WIF NEON APP_SECRETS SEED_SECRETS
                        GITHUB_CONFIG BACKEND_DEPLOY PAGES_DEPLOY VOICE_KEYS
                        MODAL_DEPLOY VERIFY
  --status              Print what the state file says and exit.
  --reset               Delete the state file and exit. Does not touch any cloud
                        resource, so the next run re-detects everything.
  -h, --help            This text.

State file: deployment/.go_live.state (gitignored, never holds secret values)
USAGE
}

die() { printf '\n  %s✗ %s%s\n\n' "$RED" "$1" "$RESET" >&2; exit 1; }
ok()  { printf '  %s✓%s %s\n' "$GREEN" "$RESET" "$1"; }
hdr() { printf '\n  %s%s%s\n' "$BOLD" "$1" "$RESET"; }

# unverified "..." - label anything whose exact console path or CLI behaviour
# could not be confirmed while this wizard was written. Being wrong quietly is
# worse than saying so.
unverified() { printf '  %s? unverified:%s %s\n' "$YELLOW" "$RESET" "$1"; }

blocker() {
  BLOCKERS+=("$1")
  printf '  %s%s✗ BLOCKER%s %s\n' "$BOLD" "$RED" "$RESET" "$1"
}

# --- argument parsing -----------------------------------------------------

while (( $# )); do
  case "$1" in
    --dry-run) DRY_RUN=1 ;;
    --force)   FORCE_ALL=1 ;;
    --force-stage)
      [[ $# -ge 2 ]] || die "--force-stage needs a stage name"
      # Catch a typo now rather than silently doing nothing all the way through.
      [[ " $STAGE_ORDER " == *" $2 "* ]] \
        || die "unknown stage '$2'. Valid stages: $STAGE_ORDER"
      FORCE_STAGES="$FORCE_STAGES $2"; shift ;;
    --status)
      if [[ -f "$ENV_FILE" ]]; then
        printf '\nState file: %s\n\n' "$ENV_FILE"
        cat "$ENV_FILE"
        printf '\n'
      else
        printf '\nNo state file yet at %s - nothing has been run.\n\n' "$ENV_FILE"
      fi
      exit 0 ;;
    --reset)
      rm -f "$ENV_FILE"
      printf '\nRemoved %s. Cloud resources were not touched.\n\n' "$ENV_FILE"
      exit 0 ;;
    -h|--help) usage; exit 0 ;;
    *) usage; die "unknown option: $1" ;;
  esac
  shift
done

# --- state ---------------------------------------------------------------

state_get() { _existing "$1" || true; }

# record KEY VALUE - persist a NON-SECRET value. Guard rail: refuse anything
# that looks like credential material, so a future edit cannot leak a key into
# a file on disk by accident.
record() {
  local key="$1" value="$2"
  case "$key" in
    *PASSWORD*|*SECRET*|*TOKEN*|*API_KEY*|DATABASE_URL|*_JWT)
      die "internal error: refusing to persist '$key' to the state file" ;;
  esac
  # A dry run must not leave a state file behind: its placeholder values would
  # come back as the "[Enter keeps current]" defaults on the next real run.
  if (( DRY_RUN )); then
    printf '  %s[dry-run]%s would record %s=%s\n' "$YELLOW" "$RESET" "$key" "$value"
    return 0
  fi
  write_env "$key" "$value"
}

is_done() { [[ "$(state_get "DONE_$1")" == "1" ]]; }

mark_done() {
  (( DRY_RUN )) && { note "(dry-run) would mark stage $1 complete"; return 0; }
  write_env "DONE_$1" "1"
}

# begin_stage MARKER "Name" MINUTES - returns 0 to run the body, 1 to skip.
# A skipped stage still consumes its slot in the progress counter so the
# "N of 12" and time-remaining numbers stay honest on a resumed run.
begin_stage() {
  local marker="$1" name="$2" mins="$3"
  if is_done "$marker" && (( ! FORCE_ALL )) && [[ " $FORCE_STAGES " != *" $marker "* ]]; then
    _STAGE_INDEX=$((_STAGE_INDEX + 1))
    _MINUTES_ELAPSED=$((_MINUTES_ELAPSED + mins))
    RESUMED+=("$marker ($name)")
    return 1
  fi
  stage "$name" "$mins"
  (( DRY_RUN )) && note "DRY RUN: nothing below will be created or changed."
  return 0
}

# --- command execution ---------------------------------------------------

# _echo_cmd cmd... - print a command exactly as it would need to be typed.
# printf %q re-quotes each argument, so a dry-run line can be copy-pasted
# verbatim instead of losing the quoting around anything with a space in it.
_echo_cmd() {
  printf '  %s           $ ' "$DIM"
  printf '%q ' "$@"
  printf '%s\n' "$RESET"
}

# run "description" cmd... - a mutating command. Printed but not executed in
# dry-run mode. Never returns non-zero (a failure warns and is recorded), so a
# single bad API call cannot abort the whole wizard under `set -e`.
#
# NOTHING SECRET MAY BE PASSED TO run(): the argv is echoed. Secret material
# always travels by stdin or a 0600 temp file instead.
run() {
  local desc="$1"; shift
  if (( DRY_RUN )); then
    printf '  %s[dry-run]%s %s\n' "$YELLOW" "$RESET" "$desc"
    _echo_cmd "$@"
    return 0
  fi
  printf '  %s→%s %s\n' "$BLUE" "$RESET" "$desc"
  if "$@"; then
    ok "$desc"
  else
    warn "failed: $desc"
    SKIPPED+=("$desc (re-run the wizard, or run: $*)")
  fi
  return 0
}

# must "description" cmd... - like run, but a failure is fatal.
must() {
  local desc="$1"; shift
  if (( DRY_RUN )); then
    printf '  %s[dry-run]%s %s\n' "$YELLOW" "$RESET" "$desc"
    _echo_cmd "$@"
    return 0
  fi
  printf '  %s→%s %s\n' "$BLUE" "$RESET" "$desc"
  "$@" || die "$desc failed. Fix the error above and re-run; completed stages will be skipped."
  ok "$desc"
}

# probe cmd... - a read-only existence check. Always executes, even in dry-run,
# because a dry-run plan is only useful if it knows what already exists.
probe() { "$@" >/dev/null 2>&1; }

# capture cmd... - a read-only value read. Empty on failure.
capture() { "$@" 2>/dev/null || true; }

# --- prompting -----------------------------------------------------------

# ask_required KEY "Prompt" "fallback" - loop until non-empty. When stdin is not
# a terminal (a piped dry run) it takes the fallback immediately instead of
# spinning on EOF forever.
ask_required() {
  local key="$1" prompt="$2" fallback="${3:-}" tries=0
  if (( NONINTERACTIVE )); then
    [[ -n "$fallback" ]] || die "non-interactive and no fallback for: $prompt"
    printf -v "$key" '%s' "$fallback"
    note "non-interactive: using '$fallback' for $prompt"
    return 0
  fi
  while :; do
    ask "$key" "$prompt"
    [[ -n "${!key}" ]] && return 0
    tries=$((tries + 1))
    (( tries >= 4 )) && die "no value given for: $prompt"
    warn "a value is required."
  done
}

# ask_secret_required KEY "Prompt" "fallback" - the hidden-input twin.
ask_secret_required() {
  local key="$1" prompt="$2" fallback="${3:-}" tries=0
  if (( NONINTERACTIVE )); then
    [[ -n "$fallback" ]] || die "non-interactive and no fallback for: $prompt"
    printf -v "$key" '%s' "$fallback"
    note "non-interactive: using a placeholder for $prompt"
    return 0
  fi
  while :; do
    ask_secret "$key" "$prompt"
    [[ -n "${!key}" ]] && return 0
    tries=$((tries + 1))
    (( tries >= 4 )) && die "no value given for: $prompt"
    warn "a value is required."
  done
}

# proceed "question" - a go/no-go gate on the happy path. Assumed yes when
# non-interactive so a piped dry run still walks the whole plan.
proceed() {
  (( NONINTERACTIVE )) && { note "(non-interactive: assuming yes) $1"; return 0; }
  confirm "$1"
}

# maybe_open_url - opening a browser is a side effect, so a dry run only says
# which page it would have opened.
maybe_open_url() {
  if (( DRY_RUN )); then
    printf '  %s[dry-run]%s would open %s\n' "$YELLOW" "$RESET" "$1"
  else
    open_url "$1"
  fi
}

# nap SECONDS - sleep, except in a dry run.
nap() { (( DRY_RUN )) || sleep "$1"; }

# --- secret plumbing -----------------------------------------------------

# One scratch directory for the whole run, created eagerly. It must NOT be
# created lazily from inside secret_file, because secret_file is always called
# in a $( ) command substitution: the assignment would happen in the subshell,
# the parent's SCRATCH would stay empty, every call would leak a new directory
# and the EXIT trap would clean up none of them.
SCRATCH=$(mktemp -d "${TMPDIR:-/tmp}/go_live.XXXXXX") || {
  printf 'could not create a temp directory\n' >&2; exit 1
}
chmod 700 "$SCRATCH"
_cleanup() {
  [[ -n "${SCRATCH:-}" && -d "$SCRATCH" ]] || return 0
  find "$SCRATCH" -type f -exec rm -f {} + 2>/dev/null || true
  rm -rf "$SCRATCH" 2>/dev/null || true
}
trap _cleanup EXIT INT TERM

# secret_file VALUE - write VALUE to a fresh 0600 file and echo the path. Used
# so secret material reaches gcloud and modal via a file rather than argv (where
# `ps` could read it) and never via the terminal or shell history.
secret_file() {
  local path
  path=$(mktemp "$SCRATCH/s.XXXXXX")
  chmod 600 "$path"
  printf '%s' "$1" > "$path"
  printf '%s' "$path"
}

gen_password() {
  if command -v openssl >/dev/null 2>&1; then
    openssl rand -base64 32 | tr -d '\n=+/' | cut -c1-32
  else
    python3 -c 'import secrets; print(secrets.token_urlsafe(32)[:32])'
  fi
}

sm_exists() {
  probe gcloud secrets describe "$1" --project "$GCP_PROJECT_ID"
}

# sm_add_version NAME VALUE - add a new version to an existing secret. The value
# travels through a 0600 file, never argv, never the screen.
sm_add_version() {
  local name="$1" value="$2" path
  if (( DRY_RUN )); then
    printf '  %s[dry-run]%s would add a new version of %s\n' "$YELLOW" "$RESET" "$name"
    printf '  %s           $ gcloud secrets versions add %s --data-file=<0600 temp file> --project %s%s\n' \
      "$DIM" "$name" "$GCP_PROJECT_ID" "$RESET"
    return 0
  fi
  path=$(secret_file "$value")
  run "add new version of $name" \
    gcloud secrets versions add "$name" --data-file="$path" --project "$GCP_PROJECT_ID"
  rm -f "$path"
}

# sm_put NAME VALUE ["what it is"] - create the secret, or add a new version if
# it already exists and the human asks to rotate.
sm_put() {
  local name="$1" value="$2" what="${3:-}" path
  if sm_exists "$name"; then
    ok "Secret Manager already has $name${what:+ ($what)}"
    if [[ -n "$value" ]] && confirm "add a NEW version of $name (rotates it)?"; then
      sm_add_version "$name" "$value"
    else
      note "keeping the existing value of $name"
    fi
    return 0
  fi
  [[ -n "$value" ]] || { warn "no value for $name, skipping"; SKIPPED+=("Secret Manager secret $name"); return 0; }
  if (( DRY_RUN )); then
    printf '  %s[dry-run]%s would create Secret Manager secret %s%s\n' \
      "$YELLOW" "$RESET" "$name" "${what:+ ($what)}"
    printf '  %s           $ gcloud secrets create %s --data-file=<0600 temp file> --project %s%s\n' \
      "$DIM" "$name" "$GCP_PROJECT_ID" "$RESET"
    return 0
  fi
  path=$(secret_file "$value")
  # --replication-policy is deliberately omitted: gcloud defaults to automatic
  # replication, and passing the flag drags in a --locations argument group.
  run "create Secret Manager secret $name${what:+ ($what)}" \
    gcloud secrets create "$name" --data-file="$path" --project "$GCP_PROJECT_ID"
  rm -f "$path"
}

sm_grant_accessor() {
  local name="$1" member="$2"
  run "grant $member read access to $name" \
    gcloud secrets add-iam-policy-binding "$name" \
      --member="serviceAccount:$member" \
      --role="roles/secretmanager.secretAccessor" \
      --project "$GCP_PROJECT_ID"
}

# --- github plumbing (dry-run aware wrappers over the library helpers) ----

gh_secret() {
  local name="$1" value="$2"
  if (( DRY_RUN )); then
    printf '  %s[dry-run]%s would set GitHub secret %s\n' "$YELLOW" "$RESET" "$name"
    return 0
  fi
  set_secret "$name" "$value"
}

gh_var() {
  local name="$1" value="$2"
  if (( DRY_RUN )); then
    printf '  %s[dry-run]%s would set GitHub variable %s=%s\n' "$YELLOW" "$RESET" "$name" "$value"
    return 0
  fi
  set_var "$name" "$value"
}

# watch_workflow FILE "label" MAX_MINUTES - poll the most recent run of FILE.
# Returns 0 on success, 1 on failure or timeout.
watch_workflow() {
  local wf="$1" label="$2" max_min="$3"
  if (( DRY_RUN )); then
    printf '  %s[dry-run]%s would poll the latest %s run until it finishes\n' "$YELLOW" "$RESET" "$wf"
    return 0
  fi
  local deadline=$(( $(date +%s) + max_min * 60 ))
  local status conclusion url=""
  say "Polling GitHub Actions. Ctrl-C is safe: the run keeps going and you can"
  say "re-run this wizard, which will pick up from here."
  while :; do
    status=$(capture gh run list --workflow "$wf" --limit 1 --json status --jq '.[0].status')
    conclusion=$(capture gh run list --workflow "$wf" --limit 1 --json conclusion --jq '.[0].conclusion')
    url=$(capture gh run list --workflow "$wf" --limit 1 --json url --jq '.[0].url')
    case "$status" in
      completed)
        if [[ "$conclusion" == "success" ]]; then ok "$label succeeded"; note "$url"; return 0; fi
        warn "$label finished with conclusion: ${conclusion:-unknown}"
        note "logs: $url"
        return 1 ;;
      "" ) note "no run visible yet, waiting..." ;;
      *  ) note "status: $status" ;;
    esac
    if (( $(date +%s) > deadline )); then
      warn "$label still not finished after ${max_min}m; check it in the browser"
      note "${url:-https://github.com/$GH_REPO_SLUG/actions}"
      return 1
    fi
    sleep 20
  done
}

probe_health() {
  local url="$1" path="$2" tries="$3" code
  if (( DRY_RUN )); then
    printf '  %s[dry-run]%s would poll %s%s until it returns 200\n' "$YELLOW" "$RESET" "$url" "$path"
    return 0
  fi
  local i
  for (( i = 1; i <= tries; i++ )); do
    code=$(capture curl -s -o /dev/null -w '%{http_code}' --max-time 25 "$url$path")
    if [[ "$code" == "200" ]]; then ok "$url$path returned 200"; return 0; fi
    note "attempt $i/$tries: $path returned ${code:-no response}"
    sleep 10
  done
  warn "$url$path never returned 200"
  return 1
}

# ==========================================================================
banner "FrontShiftAI go-live"

hdr "Before you start"
say "What this does: creates a brand new GCP project you own, wires GitHub"
say "Actions to it with Workload Identity Federation, points the backend at a"
say "free Neon Postgres, publishes the landing page and chat app to GitHub"
say "Pages, and deploys the voice agent to Modal."
printf '\n'
hdr "Where money is involved. Read this, do not skim it."
say "Cloud Run: min-instances is 0 in the deploy workflow, so an idle service"
say "costs essentially nothing. You pay per request-second while it serves."
say "A new Google Cloud account gets a \$300 / 90-day credit; billing must still"
say "be linked or the APIs will not enable."
say "Artifact Registry: you pay for stored image layers. The backend image is"
say "large (torch). Budget a few cents to a couple of dollars a month, and"
say "delete old images if it grows."
say "Neon: the free plan is genuinely free but has limits and can change."
say "Modal: monthly free credits, then per-second CPU billing while a voice"
say "worker runs. Workers exit when the call ends."
say "Deepgram / OpenAI / AssemblyAI / Cartesia / Groq / Brave / Inception: each"
say "has its own free tier or trial credit. None of them are free forever."
printf '\n'
note "Nothing here is free forever. Set a budget alert in Cloud Billing."
printf '\n'
note "State file: $ENV_FILE"
note "Re-run this script any time. Finished stages are skipped."
(( DRY_RUN )) && warn "DRY RUN: no resource will be created or modified."
pause "Understood?"

# ==========================================================================
# 1. PREFLIGHT
# ==========================================================================
if begin_stage PREFLIGHT "Preflight: tools and authentication" 4; then

  hdr "Required tools"
  MISSING=""
  for tool in gcloud gh curl git; do
    if command -v "$tool" >/dev/null 2>&1; then ok "$tool $(command -v "$tool")"
    else warn "$tool is MISSING"; MISSING="$MISSING $tool"; fi
  done
  if ! command -v openssl >/dev/null 2>&1 && ! command -v python3 >/dev/null 2>&1; then
    warn "neither openssl nor python3 found; cannot generate strong secrets"
    MISSING="$MISSING openssl"
  fi

  if [[ -n "$MISSING" ]]; then
    printf '\n'
    hdr "Install what is missing, then re-run this script"
    for tool in $MISSING; do
      case "$tool" in
        gcloud)  say "gcloud:  brew install --cask google-cloud-sdk" ;;
        gh)      say "gh:      brew install gh" ;;
        curl)    say "curl:    already on macOS; on Linux: sudo apt install curl" ;;
        git)     say "git:     brew install git" ;;
        openssl) say "openssl: brew install openssl" ;;
      esac
    done
    die "stopping before anything is configured."
  fi

  hdr "Optional tools"
  for tool in modal docker psql jq; do
    if command -v "$tool" >/dev/null 2>&1; then ok "$tool $(command -v "$tool")"
    else
      case "$tool" in
        modal)  warn "modal missing: needed only for the voice stages (pip install modal)" ;;
        docker) note "docker missing: not needed. The backend image is built inside the GitHub Actions runner, not here." ;;
        psql)   note "psql missing: the Neon credential test will be skipped (brew install libpq)" ;;
        jq)     note "jq missing: not needed, gh has --jq built in" ;;
      esac
    fi
  done

  hdr "Authentication"
  ACTIVE_GCLOUD_ACCOUNT=$(capture gcloud auth list --filter=status:ACTIVE --format='value(account)')
  if [[ -z "$ACTIVE_GCLOUD_ACCOUNT" ]]; then
    warn "gcloud has no active account."
    say "Run this, then re-run the wizard:"
    say "    gcloud auth login"
    die "not authenticated to Google Cloud."
  fi
  ok "gcloud account: $ACTIVE_GCLOUD_ACCOUNT"

  # `gcloud auth list` only reads ~/.config/gcloud on disk, so it happily
  # reports an ACTIVE account whose refresh token has since been revoked or
  # expired. Every real call then dies with "There was a problem refreshing
  # your current auth tokens: invalid_grant". So make one cheap authenticated
  # API call and find out now rather than four stages in.
  if ! probe gcloud projects list --limit=1 --format='value(projectId)'; then
    warn "gcloud has an active account on disk but its credentials do not work."
    say "That usually means the refresh token expired or was revoked. The error"
    say "you would otherwise hit later is 'invalid_grant: Bad Request'."
    say "Run this, then re-run the wizard:"
    say "    gcloud auth login"
    die "gcloud credentials are stale."
  fi
  ok "gcloud credentials are live (an authenticated API call succeeded)"

  note "This wizard passes --project explicitly on every call, so your current"
  note "gcloud default project ($(capture gcloud config get-value project)) is left alone."

  if ! gh auth status >/dev/null 2>&1; then
    warn "gh is not authenticated."
    say "Run this, then re-run the wizard:"
    say "    gh auth login --scopes repo,workflow"
    die "not authenticated to GitHub."
  fi
  GH_ACCOUNT=$(capture gh api user --jq .login)
  ok "gh account: ${GH_ACCOUNT:-unknown}, operating on $GH_REPO_SLUG"

  GH_SCOPES=$(gh auth status 2>&1 | grep -i 'token scopes' || true)
  if [[ -n "$GH_SCOPES" ]]; then
    note "$(printf '%s' "$GH_SCOPES" | sed 's/^ *//')"
    [[ "$GH_SCOPES" == *repo* ]]     || warn "the 'repo' scope is needed to set repo secrets: gh auth refresh -s repo"
    [[ "$GH_SCOPES" == *workflow* ]] || warn "the 'workflow' scope is needed for 'gh workflow run': gh auth refresh -s workflow"
  fi

  if ! probe gh repo view "$GH_REPO_SLUG"; then
    die "cannot read $GH_REPO_SLUG with this gh account."
  fi
  ok "can reach $GH_REPO_SLUG"

  record GH_REPO_SLUG "$GH_REPO_SLUG"
  mark_done PREFLIGHT
  pause "Preflight passed. Continue?"
fi

# ==========================================================================
# 2. GCP PROJECT
# ==========================================================================
if begin_stage GCP_PROJECT "Google Cloud project, billing, APIs, Artifact Registry" 12; then

  hdr "Pick a project id"
  say "A GCP project id is GLOBALLY UNIQUE across all of Google Cloud, and it can"
  say "never be changed or reused after deletion. Pick something with a suffix,"
  say "for example: frontshiftai-live-7391"
  printf '\n'
  warn "Do NOT use 'frontshiftai' or 'frontshiftai-deploy'. Those are the old"
  warn "shared group project ids. Their JWT signing key and a super-admin JWT are"
  warn "both in this repo's git history, so anything under them is compromised."
  printf '\n'
  note "Rules: 6 to 30 characters, lowercase letters, digits and hyphens, must"
  note "start with a letter and must not end with a hyphen."
  printf '\n'

  ask_required GCP_PROJECT_ID "GCP project id:" "fsai-dryrun-0000"
  for bad in $FORBIDDEN_PROJECT_IDS; do
    [[ "$GCP_PROJECT_ID" == "$bad" ]] && die "'$bad' is a burned project id. Pick a different one."
  done
  [[ "$GCP_PROJECT_ID" =~ ^[a-z][a-z0-9-]{4,28}[a-z0-9]$ ]] \
    || die "'$GCP_PROJECT_ID' is not a valid project id (6-30 chars, lowercase, start with a letter, no trailing hyphen)."
  record GCP_PROJECT_ID "$GCP_PROJECT_ID"
  record GCP_REGION "$GCP_REGION"

  hdr "Create the project"
  if probe gcloud projects describe "$GCP_PROJECT_ID"; then
    ok "project $GCP_PROJECT_ID already exists and you can see it"
  else
    say "If this fails with 'project id is not available', someone else owns that"
    say "id (it may even be deleted-but-reserved). Pick another and re-run."
    must "create project $GCP_PROJECT_ID" \
      gcloud projects create "$GCP_PROJECT_ID" --name="FrontShiftAI"
  fi

  GCP_PROJECT_NUMBER=$(capture gcloud projects describe "$GCP_PROJECT_ID" --format='value(projectNumber)')
  if [[ -z "$GCP_PROJECT_NUMBER" ]]; then
    if (( DRY_RUN )); then
      GCP_PROJECT_NUMBER="000000000000"
      note "(dry-run) project does not exist yet; using placeholder number $GCP_PROJECT_NUMBER"
    else
      die "could not read the project number for $GCP_PROJECT_ID"
    fi
  else
    ok "project number: $GCP_PROJECT_NUMBER"
    record GCP_PROJECT_NUMBER "$GCP_PROJECT_NUMBER"
  fi

  hdr "Link billing"
  BILLING_ENABLED=$(capture gcloud billing projects describe "$GCP_PROJECT_ID" --format='value(billingEnabled)')
  if [[ "$BILLING_ENABLED" == "True" || "$BILLING_ENABLED" == "true" ]]; then
    ok "billing is already enabled on $GCP_PROJECT_ID"
  else
    say "Without billing, 'gcloud services enable' fails and nothing else works."
    BILLING_ACCOUNTS=$(capture gcloud billing accounts list --filter='open=true' --format='value(name)')
    if [[ -z "$BILLING_ACCOUNTS" ]]; then
      warn "no open billing account found on this Google account."
      maybe_open_url "https://console.cloud.google.com/billing"
      step "Create a billing account. A new account gets a \$300 / 90-day credit."
      step "Come back and re-run this wizard, or link it by hand:"
      note "    gcloud billing projects link $GCP_PROJECT_ID --billing-account=<ACCOUNT_ID>"
      SKIPPED+=("link a billing account to $GCP_PROJECT_ID")
    else
      say "Open billing accounts:"
      capture gcloud billing accounts list --filter='open=true' \
        --format='table(name,displayName,open)' | sed 's/^/    /'
      BILLING_DEFAULT=$(printf '%s\n' "$BILLING_ACCOUNTS" | head -n1 | sed 's|^billingAccounts/||')
      ask_required BILLING_ACCOUNT_ID "Billing account id [$BILLING_DEFAULT]:" "$BILLING_DEFAULT"
      [[ -n "$BILLING_ACCOUNT_ID" ]] || BILLING_ACCOUNT_ID="$BILLING_DEFAULT"
      BILLING_ACCOUNT_ID="${BILLING_ACCOUNT_ID#billingAccounts/}"
      must "link billing account $BILLING_ACCOUNT_ID" \
        gcloud billing projects link "$GCP_PROJECT_ID" --billing-account="$BILLING_ACCOUNT_ID"
    fi
  fi

  hdr "Enable APIs"
  note "compute.googleapis.com is on the list on purpose: Cloud Run's default"
  note "runtime identity is the Compute Engine default service account, and that"
  note "account only exists once the Compute API has been enabled."
  ENABLED_APIS=$(capture gcloud services list --enabled --project "$GCP_PROJECT_ID" --format='value(config.name)')
  TO_ENABLE=""
  for api in $REQUIRED_APIS; do
    if [[ "$ENABLED_APIS" == *"$api"* ]]; then ok "$api already enabled"
    else TO_ENABLE="$TO_ENABLE $api"; fi
  done
  if [[ -n "$TO_ENABLE" ]]; then
    note "this can take a couple of minutes"
    # Word splitting of the API list is deliberate: gcloud takes them as
    # separate positional arguments.
    # shellcheck disable=SC2086
    must "enable APIs:$TO_ENABLE" \
      gcloud services enable $TO_ENABLE --project "$GCP_PROJECT_ID"
  fi

  hdr "Artifact Registry"
  note "deploy-backend.yml pushes to"
  note "  $GCP_REGION-docker.pkg.dev/$GCP_PROJECT_ID/$ARTIFACT_REPOSITORY/backend"
  note "so the repo name and region below are not free choices."
  if probe gcloud artifacts repositories describe "$ARTIFACT_REPOSITORY" \
      --location="$GCP_REGION" --project "$GCP_PROJECT_ID"; then
    ok "Artifact Registry repo $ARTIFACT_REPOSITORY already exists in $GCP_REGION"
  else
    must "create Artifact Registry repo $ARTIFACT_REPOSITORY in $GCP_REGION" \
      gcloud artifacts repositories create "$ARTIFACT_REPOSITORY" \
        --repository-format=docker \
        --location="$GCP_REGION" \
        --description="FrontShiftAI backend images" \
        --project "$GCP_PROJECT_ID"
  fi
  record ARTIFACT_REPOSITORY "$ARTIFACT_REPOSITORY"
  record CLOUD_RUN_SERVICE "$CLOUD_RUN_SERVICE"

  mark_done GCP_PROJECT
  pause "Project ready. Continue?"
fi

# Re-hydrate anything a later stage needs, in case this run skipped Stage 2.
GCP_PROJECT_ID="${GCP_PROJECT_ID:-$(state_get GCP_PROJECT_ID)}"
GCP_PROJECT_NUMBER="${GCP_PROJECT_NUMBER:-$(state_get GCP_PROJECT_NUMBER)}"
[[ -n "$GCP_PROJECT_ID" ]] || die "no GCP project id in the state file. Re-run with --force-stage GCP_PROJECT."

# ==========================================================================
# 3. WORKLOAD IDENTITY FEDERATION
# ==========================================================================
if begin_stage WIF "Workload Identity Federation for GitHub Actions" 8; then

  DEPLOY_SA_EMAIL="$DEPLOY_SA_ID@$GCP_PROJECT_ID.iam.gserviceaccount.com"

  hdr "Why this exists"
  say "deploy-backend.yml authenticates with google-github-actions/auth@v2 using"
  say "Workload Identity Federation, so there is no long-lived JSON key to leak."
  say "GitHub mints an OIDC token, GCP trades it for a short-lived access token"
  say "for the deploy service account, and only for this one repository."
  printf '\n'

  hdr "Deploy service account"
  if probe gcloud iam service-accounts describe "$DEPLOY_SA_EMAIL" --project "$GCP_PROJECT_ID"; then
    ok "service account $DEPLOY_SA_EMAIL already exists"
  else
    must "create service account $DEPLOY_SA_ID" \
      gcloud iam service-accounts create "$DEPLOY_SA_ID" \
        --display-name="GitHub Actions Deployer" \
        --project "$GCP_PROJECT_ID"
  fi

  hdr "Workload identity pool"
  if probe gcloud iam workload-identity-pools describe "$WIF_POOL" \
      --location=global --project "$GCP_PROJECT_ID"; then
    ok "pool $WIF_POOL already exists"
    note "If you ever delete a pool, the id is soft-deleted for 30 days. Recover"
    note "it with: gcloud iam workload-identity-pools undelete $WIF_POOL --location=global"
  else
    must "create workload identity pool $WIF_POOL" \
      gcloud iam workload-identity-pools create "$WIF_POOL" \
        --location=global \
        --display-name="GitHub Actions Pool" \
        --project "$GCP_PROJECT_ID"
  fi

  hdr "OIDC provider"
  say "The attribute condition below is what stops any other repository on"
  say "GitHub from impersonating your deploy service account. Google also"
  say "requires a condition for well-known public issuers, so it is not optional."
  if probe gcloud iam workload-identity-pools providers describe "$WIF_PROVIDER" \
      --location=global --workload-identity-pool="$WIF_POOL" --project "$GCP_PROJECT_ID"; then
    ok "provider $WIF_PROVIDER already exists"
  else
    must "create OIDC provider $WIF_PROVIDER pinned to $GH_REPO_SLUG" \
      gcloud iam workload-identity-pools providers create-oidc "$WIF_PROVIDER" \
        --location=global \
        --workload-identity-pool="$WIF_POOL" \
        --display-name="GitHub OIDC" \
        --issuer-uri="https://token.actions.githubusercontent.com" \
        --attribute-mapping="google.subject=assertion.sub,attribute.actor=assertion.actor,attribute.repository=assertion.repository,attribute.repository_owner=assertion.repository_owner" \
        --attribute-condition="assertion.repository=='$GH_REPO_SLUG'" \
        --project "$GCP_PROJECT_ID"
  fi

  hdr "Let only this repo impersonate the deploy account"
  WIF_MEMBER="principalSet://iam.googleapis.com/projects/$GCP_PROJECT_NUMBER/locations/global/workloadIdentityPools/$WIF_POOL/attribute.repository/$GH_REPO_SLUG"
  run "bind roles/iam.workloadIdentityUser for $GH_REPO_SLUG" \
    gcloud iam service-accounts add-iam-policy-binding "$DEPLOY_SA_EMAIL" \
      --role="roles/iam.workloadIdentityUser" \
      --member="$WIF_MEMBER" \
      --project "$GCP_PROJECT_ID"

  hdr "Project roles the deploy actually needs"
  note "run.admin           deploy revisions, update traffic, allow-unauthenticated"
  note "artifactregistry.writer  push the backend image"
  note "iam.serviceAccountUser   act as the Cloud Run runtime service account"
  note "secretmanager.viewer     let 'gcloud run deploy --set-secrets' pre-check"
  note "                         that each named secret exists, instead of"
  note "                         failing with an opaque permission error"
  for role in roles/run.admin roles/artifactregistry.writer roles/iam.serviceAccountUser roles/secretmanager.viewer; do
    run "grant $role to the deploy account" \
      gcloud projects add-iam-policy-binding "$GCP_PROJECT_ID" \
        --member="serviceAccount:$DEPLOY_SA_EMAIL" \
        --role="$role" \
        --condition=None
  done

  hdr "Cloud Run runtime service account"
  say "deploy-backend.yml does not pass --service-account, so the service runs as"
  say "the Compute Engine default account. That is the identity that has to be"
  say "able to read the Secret Manager entries."
  RUNTIME_SA_EMAIL=""
  for attempt in 1 2 3 4 5 6; do
    RUNTIME_SA_EMAIL=$(capture gcloud iam service-accounts list \
      --project "$GCP_PROJECT_ID" \
      --filter="email~compute@developer.gserviceaccount.com" \
      --format='value(email)' | head -n1)
    [[ -n "$RUNTIME_SA_EMAIL" ]] && break
    if (( DRY_RUN )); then
      note "(dry-run) would poll for the default compute service account, up to 6 times"
      break
    fi
    note "not created yet (attempt $attempt/6), waiting 10s..."
    nap 10
  done
  if [[ -z "$RUNTIME_SA_EMAIL" ]]; then
    RUNTIME_SA_EMAIL="$GCP_PROJECT_NUMBER-compute@developer.gserviceaccount.com"
    warn "could not confirm the default compute service account exists."
    warn "Assuming $RUNTIME_SA_EMAIL. If Stage 8's deploy fails with 'service"
    warn "account does not exist', enable compute.googleapis.com and re-run"
    warn "with --force-stage WIF."
  else
    ok "runtime service account: $RUNTIME_SA_EMAIL"
  fi

  hdr "The value that goes into GitHub"
  WIF_PROVIDER_RESOURCE=$(capture gcloud iam workload-identity-pools providers describe "$WIF_PROVIDER" \
    --location=global --workload-identity-pool="$WIF_POOL" \
    --project "$GCP_PROJECT_ID" --format='value(name)')
  if [[ -z "$WIF_PROVIDER_RESOURCE" ]]; then
    WIF_PROVIDER_RESOURCE="projects/$GCP_PROJECT_NUMBER/locations/global/workloadIdentityPools/$WIF_POOL/providers/$WIF_PROVIDER"
    (( DRY_RUN )) || warn "could not read the provider resource name; using the constructed form"
  fi
  printf '\n'
  say "GCP_WORKLOAD_IDENTITY_PROVIDER:"
  printf '    %s%s%s\n' "$BOLD" "$WIF_PROVIDER_RESOURCE" "$RESET"
  say "GCP_SERVICE_ACCOUNT:"
  printf '    %s%s%s\n' "$BOLD" "$DEPLOY_SA_EMAIL" "$RESET"
  printf '\n'
  note "Stage 7 writes both of these into the repo secrets for you."

  record DEPLOY_SERVICE_ACCOUNT "$DEPLOY_SA_EMAIL"
  record RUNTIME_SERVICE_ACCOUNT "$RUNTIME_SA_EMAIL"
  record GCP_WORKLOAD_IDENTITY_PROVIDER "$WIF_PROVIDER_RESOURCE"
  mark_done WIF
  pause "Federation configured. Continue?"
fi

DEPLOY_SA_EMAIL="${DEPLOY_SA_EMAIL:-$(state_get DEPLOY_SERVICE_ACCOUNT)}"
RUNTIME_SA_EMAIL="${RUNTIME_SA_EMAIL:-$(state_get RUNTIME_SERVICE_ACCOUNT)}"
WIF_PROVIDER_RESOURCE="${WIF_PROVIDER_RESOURCE:-$(state_get GCP_WORKLOAD_IDENTITY_PROVIDER)}"

# ==========================================================================
# 4. NEON POSTGRES
# ==========================================================================
if begin_stage NEON "Neon Postgres and the DATABASE_URL secret" 10; then

  hdr "Why Neon and not Cloud SQL"
  say "backend/db/connection.py refuses to start when ENVIRONMENT=production and"
  say "DATABASE_URL is unset: there is no SQLite fallback any more, because on"
  say "Cloud Run a SQLite file dies with the container. deploy-backend.yml passes"
  say "--clear-cloudsql-instances, so there is no Cloud SQL socket either. The"
  say "backend reaches Neon over ordinary TLS from the public internet."
  printf '\n'
  note "Neon's free plan needs no card. It does have storage and compute-hour"
  note "limits, and a free-plan branch auto-suspends when idle, which adds a few"
  note "hundred ms to the first query after a quiet period."
  printf '\n'

  maybe_open_url "https://console.neon.tech/signup"
  step "Sign up or log in (GitHub login is fine)."
  step "Create a project. Name it FrontShiftAI."
  step "For the region, pick whatever is closest to us-central1, which is where"
  step "Cloud Run runs. Neon does not offer GCP us-central1 on the free plan, so"
  step "a US East or US West region is the practical answer. Expect a few tens of"
  step "ms of extra latency per query."
  unverified "Neon's exact region list and console wording change often. Pick the"
  unverified "closest US region on offer."
  step "On the project dashboard find the Connect / Connection string panel."
  step "Turn ON 'Connection pooling' (the host then contains '-pooler')."
  printf '\n'
  say "Why pooled: connection.py uses QueuePool(pool_size=5, max_overflow=10),"
  say "so one Cloud Run instance can hold 15 connections and the workflow allows"
  say "up to 10 instances. 150 direct connections would exceed a free Neon"
  say "compute; the pooler endpoint absorbs that."
  step "Copy the whole connection string. It looks like:"
  note "    postgresql://USER:PASSWORD@ep-xxxx-pooler.us-east-2.aws.neon.tech/neondb?sslmode=require"
  printf '\n'
  warn "This string contains a password. It is read hidden, is never printed, is"
  warn "never written to the state file, and reaches gcloud through a 0600 temp"
  warn "file rather than the command line."
  printf '\n'

  ask_secret_required NEON_DATABASE_URL "Paste the Neon connection string:" \
    "postgresql://dryrun:dryrun@ep-dry-run-pooler.us-east-2.aws.neon.tech/neondb?sslmode=require"

  hdr "Validating the shape"
  case "$NEON_DATABASE_URL" in
    postgresql://*) ok "scheme is postgresql://" ;;
    postgres://*)
      warn "scheme is postgres://. SQLAlchemy 2 wants postgresql://, and"
      warn "connection.py branches on url.startswith('postgresql'), so postgres://"
      warn "would silently fall through to the 'unknown dialect' path."
      if proceed "rewrite it to postgresql:// ?"; then
        NEON_DATABASE_URL="postgresql://${NEON_DATABASE_URL#postgres://}"
        ok "rewritten to postgresql://"
      fi ;;
    *) die "that does not start with postgresql:// or postgres://" ;;
  esac

  NEON_AFTER_AT="${NEON_DATABASE_URL#*@}"
  NEON_HOSTPORT="${NEON_AFTER_AT%%/*}"
  NEON_HOST="${NEON_HOSTPORT%%:*}"
  [[ -n "$NEON_HOST" && "$NEON_HOST" != "$NEON_DATABASE_URL" ]] \
    || die "could not find a host in that connection string (expected user:pass@host/db)."
  [[ "$NEON_DATABASE_URL" == *"@"* ]] || die "no credentials found before the host."
  ok "host: $NEON_HOST"

  NEON_PATH="${NEON_AFTER_AT#*/}"
  NEON_DBNAME="${NEON_PATH%%\?*}"
  [[ -n "$NEON_DBNAME" ]] || die "no database name found after the host."
  ok "database: $NEON_DBNAME"

  if [[ "$NEON_DATABASE_URL" == *"sslmode=require"* ]]; then
    ok "sslmode=require is present"
  else
    warn "sslmode=require is missing. Neon requires TLS and will reject the"
    warn "connection without it."
    if proceed "append sslmode=require ?"; then
      if [[ "$NEON_DATABASE_URL" == *"?"* ]]; then
        NEON_DATABASE_URL="$NEON_DATABASE_URL&sslmode=require"
      else
        NEON_DATABASE_URL="$NEON_DATABASE_URL?sslmode=require"
      fi
      ok "appended sslmode=require"
    else
      warn "continuing without it. Expect the backend to fail to connect."
    fi
  fi

  if [[ "$NEON_HOST" == *-pooler.* ]]; then
    ok "this is the pooled endpoint, which is what you want"
  else
    warn "this looks like the DIRECT endpoint (no '-pooler' in the host)."
    warn "It will work, but 10 Cloud Run instances x 15 pooled connections can"
    warn "exhaust a free Neon compute. Prefer the pooled string."
  fi

  hdr "Connectivity check"
  if command -v psql >/dev/null 2>&1; then
    if proceed "test the credentials with psql?"; then
      if (( DRY_RUN )); then
        note "(dry-run) would run: psql <connection-string> -c 'select 1'"
      else
        note "the connection string is briefly visible in your local process list"
        note "while psql runs; nothing is written to your shell history"
        if PGCONNECT_TIMEOUT=10 psql "$NEON_DATABASE_URL" -tAc 'select 1' >/dev/null 2>&1; then
          ok "psql connected and ran 'select 1'"
        else
          warn "psql could not connect. Check the string, and that the Neon"
          warn "project is not suspended or still provisioning."
          proceed "continue anyway?" || die "stopping so you can fix the connection string."
        fi
      fi
    fi
    unverified "the psql invocation above was written from psql's documented"
    unverified "connection-URI support but could not be executed here: psql is"
    unverified "not installed on the machine this wizard was authored on."
  elif command -v python3 >/dev/null 2>&1; then
    note "psql is not installed, so falling back to a TCP reachability test."
    note "This proves DNS resolves and the port accepts a connection. It does"
    note "NOT prove the username and password are right."
    if (( DRY_RUN )); then
      note "(dry-run) would open a TCP socket to $NEON_HOST:5432"
    else
      if NEON_TEST_HOST="$NEON_HOST" python3 -c '
import os, socket, sys
host = os.environ["NEON_TEST_HOST"]
try:
    socket.create_connection((host, 5432), timeout=10).close()
except Exception as exc:
    print(exc, file=sys.stderr); sys.exit(1)
' 2>/dev/null; then
        ok "$NEON_HOST:5432 is reachable"
      else
        warn "could not reach $NEON_HOST:5432. Check the host name."
      fi
    fi
  else
    note "no psql and no python3, skipping the connectivity check."
    note "Stage 8's /health/ready probe is the real test either way."
  fi

  hdr "Store it as the DATABASE_URL secret"
  sm_put DATABASE_URL "$NEON_DATABASE_URL" "Neon connection string"
  unset NEON_DATABASE_URL

  record NEON_HOST "$NEON_HOST"
  record NEON_DATABASE "$NEON_DBNAME"
  mark_done NEON
  pause "Database ready. Continue?"
fi

# ==========================================================================
# 5. APPLICATION SECRETS
# ==========================================================================
if begin_stage APP_SECRETS "Application secrets in Secret Manager" 12; then

  hdr "What deploy-backend.yml mounts"
  say "The workflow's --set-secrets names exactly these five:"
  for s in $BACKEND_SECRETS; do note "  $s"; done
  printf '\n'
  warn "gcloud run deploy FAILS if any named secret does not exist. So all five"
  warn "must be created, even the ones you do not have a real key for yet."
  printf '\n'

  # --- JWT_SECRET_KEY ---
  hdr "JWT_SECRET_KEY"
  say "backend/api/auth.py raises ValueError at import time when this is unset,"
  say "so the container cannot even start without it."
  printf '\n'
  warn "The previous signing key was committed to this repository, so it is"
  warn "burned: anyone with the git history can mint a valid super-admin token"
  warn "against any backend still using it. This generates a fresh one."
  if sm_exists JWT_SECRET_KEY; then
    ok "JWT_SECRET_KEY already exists in Secret Manager"
    if confirm "rotate it to a brand new value (every live session is invalidated)?"; then
      JWT_VALUE=$(gen_password)$(gen_password)
      sm_add_version JWT_SECRET_KEY "$JWT_VALUE"
      unset JWT_VALUE
    fi
  else
    JWT_VALUE=$(gen_password)$(gen_password)
    note "generated a 64-character random key. It is not shown and not stored"
    note "locally: Secret Manager is the only copy."
    sm_put JWT_SECRET_KEY "$JWT_VALUE" "signs backend access tokens"
    unset JWT_VALUE
  fi

  # --- GROQ_API_KEY ---
  hdr "GROQ_API_KEY"
  say "Groq is the agents' primary LLM (backend/agents/utils/llm_config.py sets"
  say "USE_LLM = 'groq'), and the RAG generator's fallback."
  if sm_exists GROQ_API_KEY; then
    ok "GROQ_API_KEY already exists"
    note "to replace it: gcloud secrets versions add GROQ_API_KEY --data-file=- --project $GCP_PROJECT_ID"
  else
    maybe_open_url "https://console.groq.com/keys"
    step "Log in, click Create API Key, copy it (it starts with gsk_)."
    note "Groq's free tier is rate limited per minute and per day and can change."
    ask_secret_required GROQ_API_KEY_VALUE "Paste the Groq API key:" "gsk_dryrun_placeholder"
    sm_put GROQ_API_KEY "$GROQ_API_KEY_VALUE" "primary LLM"
    unset GROQ_API_KEY_VALUE
  fi

  # --- BRAVE_API_KEY ---
  hdr "BRAVE_API_KEY"
  say "Used for web search and extraction when the handbook corpus has no answer."
  if sm_exists BRAVE_API_KEY; then
    ok "BRAVE_API_KEY already exists"
  else
    maybe_open_url "https://api-dashboard.search.brave.com/app/keys"
    step "Subscribe to a Search API plan, then create an API key."
    unverified "Brave's free plan tiers and whether a card is required to activate"
    unverified "one change; check the plan page before assuming it costs nothing."
    say "No key? Enter a placeholder. The secret must exist or the deploy fails."
    say "Web search will simply return errors until you rotate in a real key."
    ask_secret_required BRAVE_API_KEY_VALUE "Paste the Brave API key (or a placeholder):" "placeholder-not-set"
    sm_put BRAVE_API_KEY "$BRAVE_API_KEY_VALUE" "web search"
    unset BRAVE_API_KEY_VALUE
  fi

  # --- INCEPTION_API_KEY ---
  hdr "INCEPTION_API_KEY"
  say "deploy-backend.yml sets GENERATION_BACKEND=mercury, and"
  say "chat_pipeline/rag/generator.py reads INCEPTION_API_KEY plus"
  say "INCEPTION_API_BASE (default https://api.inceptionlabs.ai/v1) for Mercury."
  say "So this key is what actually answers chat questions in production."
  if sm_exists INCEPTION_API_KEY; then
    ok "INCEPTION_API_KEY already exists"
  else
    maybe_open_url "https://platform.inceptionlabs.ai/"
    unverified "the Inception Labs dashboard URL. generator.py only pins the API"
    unverified "base (api.inceptionlabs.ai/v1), not the console address. If that"
    unverified "page 404s, find the key in your Inception Labs account."
    say "No Mercury key? Enter a placeholder, then either:"
    note "  a) rotate a real key in later, or"
    note "  b) change GENERATION_BACKEND from 'mercury' to 'groq' in"
    note "     .github/workflows/deploy-backend.yml so the generator uses Groq."
    note "     That is a workflow edit, which this wizard deliberately does not make."
    ask_secret_required INCEPTION_API_KEY_VALUE "Paste the Inception / Mercury API key (or a placeholder):" "placeholder-not-set"
    sm_put INCEPTION_API_KEY "$INCEPTION_API_KEY_VALUE" "Mercury generation"
    unset INCEPTION_API_KEY_VALUE
  fi

  hdr "Known inconsistency you should decide about: Mercury has two names"
  say "chat_pipeline/rag/generator.py  reads INCEPTION_API_KEY / INCEPTION_API_BASE"
  say "backend/agents/utils/llm_client.py reads MERCURY_API_KEY / MERCURY_API_URL"
  printf '\n'
  say "deploy-backend.yml only supplies the INCEPTION_* pair. The consequence:"
  say "llm_config.py sets FALLBACK_CHAIN = ['groq', 'mercury', 'openai', 'local'],"
  say "so when Groq rate-limits, the agents try Mercury, _call_mercury raises"
  say "'Mercury credentials not configured' immediately, then tries OpenAI, whose"
  say "key is also not in the workflow, then 'local' Ollama, which does not exist"
  say "on Cloud Run. Net effect: the agents have Groq and nothing else."
  printf '\n'
  say "Your options, in order of effort:"
  note "  1. Accept it. Chat/RAG still works via Mercury; only the AGENTS lose"
  note "     their fallback chain. This is the do-nothing option."
  note "  2. Add MERCURY_API_URL and MERCURY_API_KEY to the workflow's"
  note "     --set-secrets, with MERCURY_API_URL = https://api.inceptionlabs.ai/v1"
  note "     and MERCURY_API_KEY = the same Inception key. That is a one-line"
  note "     workflow edit plus two more Secret Manager entries."
  note "  3. Add OPENAI_API_KEY to the workflow instead, and let OpenAI be the"
  note "     agents' fallback."
  printf '\n'
  warn "Fixing the naming mismatch in code is NOT this wizard's job. It only"
  warn "tells you it exists."
  if proceed "create MERCURY_API_URL and MERCURY_API_KEY secrets now, so option 2 is one workflow edit away?"; then
    sm_put MERCURY_API_URL "https://api.inceptionlabs.ai/v1" "agents' Mercury base URL"
    say "Paste the same Inception key again for MERCURY_API_KEY (it is not kept"
    say "in memory between prompts)."
    ask_secret_required MERCURY_KEY_VALUE "Paste the Mercury / Inception API key:" "placeholder-not-set"
    sm_put MERCURY_API_KEY "$MERCURY_KEY_VALUE" "agents' Mercury key"
    unset MERCURY_KEY_VALUE
    printf '\n'
    warn "These two are NOT mounted by the workflow yet. Add them to the"
    warn "--set-secrets list in .github/workflows/deploy-backend.yml or they do"
    warn "nothing:"
    note "  ...,MERCURY_API_URL=MERCURY_API_URL:latest,MERCURY_API_KEY=MERCURY_API_KEY:latest"
    SKIPPED+=("add MERCURY_API_URL and MERCURY_API_KEY to --set-secrets in deploy-backend.yml")
  fi

  hdr "Let the Cloud Run runtime account read the secrets"
  say "Runtime identity: ${RUNTIME_SA_EMAIL:-unknown}"
  note "Granting per secret rather than project-wide, so this account can read"
  note "only what the service actually mounts. The project-wide alternative is:"
  note "  gcloud projects add-iam-policy-binding $GCP_PROJECT_ID \\"
  note "    --member=serviceAccount:${RUNTIME_SA_EMAIL:-RUNTIME_SA} \\"
  note "    --role=roles/secretmanager.secretAccessor"
  if [[ -z "$RUNTIME_SA_EMAIL" ]]; then
    blocker "no runtime service account known; cannot grant secret access."
    SKIPPED+=("grant roles/secretmanager.secretAccessor to the Cloud Run runtime service account")
  else
    for s in $BACKEND_SECRETS; do
      if sm_exists "$s" || (( DRY_RUN )); then
        sm_grant_accessor "$s" "$RUNTIME_SA_EMAIL"
      else
        warn "$s does not exist, so it cannot be granted"
      fi
    done
  fi

  mark_done APP_SECRETS
  pause "Secrets stored. Continue?"
fi

# ==========================================================================
# 6. SEED PASSWORDS  (and the blocker they expose)
# ==========================================================================
if begin_stage SEED_SECRETS "Seed passwords, and a blocker you must know about" 8; then

  hdr "What backend/db/seed.py does"
  say "backend/main.py's lifespan calls seed_initial_data() on every startup."
  say "seed.py resolves four passwords BEFORE it opens a session, and its"
  say "_seed_password() raises RuntimeError when ENVIRONMENT=production and the"
  say "variable is unset. That happens on every cold start, not just the first,"
  say "because the 'already seeded, skipping' check comes after it."
  printf '\n'
  say "So in production the container cannot start unless all four of these are"
  say "in its environment:"
  for s in $SEED_SECRET_NAMES; do note "  $s"; done
  printf '\n'

  hdr "Choose the passwords"
  say "These become real login credentials on your public demo. Leave a prompt"
  say "empty to have a 32-character random one generated instead."
  note "SEED_SUPER_ADMIN_PASSWORD logs in as admin@frontshiftai.com (or whatever"
  note "SEED_SUPER_ADMIN_EMAIL says) with full cross-company access."
  note "SEED_DEMO_PASSWORD is the public demo account, demo@crousemedical.com,"
  note "a plain USER scoped to Crouse Medical Practice. This is the one you hand"
  note "to strangers, so pick something you are happy to publish."
  printf '\n'
  for s in $SEED_SECRET_NAMES; do
    if sm_exists "$s"; then
      ok "$s already exists in Secret Manager"
      continue
    fi
    if (( NONINTERACTIVE )); then
      SEED_VALUE=$(gen_password)
      note "non-interactive: generating $s"
    else
      ask_secret SEED_INPUT "$s (Enter to generate):"
      if [[ -n "$SEED_INPUT" ]]; then
        SEED_VALUE="$SEED_INPUT"
      else
        SEED_VALUE=$(gen_password)
        note "generated a random $s"
      fi
      unset SEED_INPUT
    fi
    sm_put "$s" "$SEED_VALUE" "seed password"
    unset SEED_VALUE
  done
  printf '\n'
  warn "Generated passwords are only in Secret Manager. Read one back with:"
  note "  gcloud secrets versions access latest --secret=SEED_DEMO_PASSWORD --project $GCP_PROJECT_ID"

  if [[ -n "$RUNTIME_SA_EMAIL" ]]; then
    hdr "Grant read access"
    for s in $SEED_SECRET_NAMES; do
      if sm_exists "$s" || (( DRY_RUN )); then
        sm_grant_accessor "$s" "$RUNTIME_SA_EMAIL"
      fi
    done
  fi

  hdr "The blocker"
  BACKEND_WORKFLOW_PATH="$REPO_ROOT/.github/workflows/$BACKEND_WORKFLOW"
  SEED_MOUNTED=0
  if [[ -f "$BACKEND_WORKFLOW_PATH" ]] && grep -q 'SEED_SUPER_ADMIN_PASSWORD' "$BACKEND_WORKFLOW_PATH"; then
    SEED_MOUNTED=1
  fi
  if (( SEED_MOUNTED )); then
    ok "$BACKEND_WORKFLOW already references SEED_SUPER_ADMIN_PASSWORD"
    record SEED_MOUNTED_IN_WORKFLOW "1"
  else
    blocker "$BACKEND_WORKFLOW does not mount the SEED_* secrets, so the first deploy will fail."
    printf '\n'
    say "Sequence: Cloud Run starts the container, the lifespan"
    say "calls seed_initial_data(), _seed_password('SEED_SUPER_ADMIN_PASSWORD')"
    say "raises, startup aborts, /health/ready never returns 200, the workflow's"
    say "18-attempt health gate gives up and rolls traffic back, and the run goes"
    say "red."
    printf '\n'
    say "Why the wizard cannot fix it: gcloud run deploy --set-secrets REPLACES"
    say "the whole secret list on every revision, so adding them by hand with"
    say "'gcloud run services update --update-secrets' survives exactly until the"
    say "next CI deploy wipes it. The list has to change in the workflow."
    printf '\n'
    say "The edit, in .github/workflows/$BACKEND_WORKFLOW, on the --set-secrets"
    say "line of the 'Deploy to Cloud Run' step. Append:"
    printf '\n'
    printf '    %s%s%s\n' "$BOLD" ",SEED_SUPER_ADMIN_PASSWORD=SEED_SUPER_ADMIN_PASSWORD:latest,SEED_ADMIN_PASSWORD=SEED_ADMIN_PASSWORD:latest,SEED_USER_PASSWORD=SEED_USER_PASSWORD:latest,SEED_DEMO_PASSWORD=SEED_DEMO_PASSWORD:latest" "$RESET"
    printf '\n'
    say "Editing workflows is outside this wizard's remit, so it stops short and"
    say "tells you. Stage 8 will refuse to switch the deploy gate on until this"
    say "is done, unless you override it there."
    SKIPPED+=("add the four SEED_* entries to --set-secrets in .github/workflows/$BACKEND_WORKFLOW")
    record SEED_MOUNTED_IN_WORKFLOW "0"
  fi

  mark_done SEED_SECRETS
  pause "Understood? Continue?"
fi

# ==========================================================================
# 7. GITHUB SECRETS AND VARIABLES
# ==========================================================================
if begin_stage GITHUB_CONFIG "GitHub repo secrets and variables" 5; then

  hdr "The three secrets deploy-backend.yml reads"
  note "GCP_PROJECT_ID                  env: PROJECT_ID"
  note "GCP_SERVICE_ACCOUNT             google-github-actions/auth service_account"
  note "GCP_WORKLOAD_IDENTITY_PROVIDER  google-github-actions/auth workload_identity_provider"
  printf '\n'
  note "A project id is not really a secret, but the workflow reads it from the"
  note "secrets context, so that is where it goes. One side effect worth knowing:"
  note "Actions masks it in logs, so build output shows *** where the project id"
  note "should be, which makes failures harder to read."
  printf '\n'

  gh_secret GCP_PROJECT_ID "$GCP_PROJECT_ID"
  gh_secret GCP_SERVICE_ACCOUNT "$DEPLOY_SA_EMAIL"
  gh_secret GCP_WORKLOAD_IDENTITY_PROVIDER "$WIF_PROVIDER_RESOURCE"

  hdr "The gate: DEPLOY_BACKEND_ENABLED"
  say "deploy-backend.yml's job-level if is:"
  note "  vars.DEPLOY_BACKEND_ENABLED == 'true' && (...)"
  printf '\n'
  say "It exists because the workflow also triggers on every push to main that"
  say "touches backend/**. Before the infrastructure existed, each of those runs"
  say "could only fail, and each failure emailed you. The gate keeps the deploy"
  say "off until you say so. It is a variable, not a secret, because the secrets"
  say "context is not available in a job-level if."
  printf '\n'
  note "It must be the literal string 'true'. Anything else, including 'True',"
  note "skips the job."
  gh_var DEPLOY_BACKEND_ENABLED "false"
  ok "gate set to 'false' for now; Stage 8 flips it to 'true'"

  hdr "The Pages build variables"
  say "deploy-pages.yml bakes these into the chat app bundle at build time:"
  note "  BACKEND_URL    -> VITE_API_URL"
  note "  VOICE_API_URL  -> VITE_VOICE_API_URL"
  say "They are variables, not secrets, because they end up readable in a"
  say "client-side bundle. Unset, the build still succeeds and the app falls back"
  say "to localhost, which is useless in production but not a build failure."
  say "Stage 9 sets BACKEND_URL and Stage 11 sets VOICE_API_URL, once those URLs"
  say "actually exist."

  mark_done GITHUB_CONFIG
  pause "GitHub configured. Continue?"
fi

# ==========================================================================
# 8. FIRST BACKEND DEPLOY
# ==========================================================================
if begin_stage BACKEND_DEPLOY "First backend deploy to Cloud Run, and verify" 20; then

  hdr "What is about to happen"
  say "Flipping DEPLOY_BACKEND_ENABLED to 'true' and dispatching"
  say "$BACKEND_WORKFLOW. In the runner: docker build of Dockerfile.backend"
  say "(torch and the MiniLM embedding model, so it is a big image and a slow"
  say "build), push to Artifact Registry, gcloud run deploy at 2Gi / 2 CPU /"
  say "max-instances 10 / min-instances 0, then up to 18 attempts at"
  say "/health/ready with a 5s gap, rolling traffic back to the previous revision"
  say "if it never goes green."
  printf '\n'
  note "Expect 10 to 25 minutes for the first run. Almost all of it is the build."
  printf '\n'

  SEED_MOUNTED_STATE=$(state_get SEED_MOUNTED_IN_WORKFLOW)
  BACKEND_WORKFLOW_PATH="$REPO_ROOT/.github/workflows/$BACKEND_WORKFLOW"
  if [[ -f "$BACKEND_WORKFLOW_PATH" ]] && grep -q 'SEED_SUPER_ADMIN_PASSWORD' "$BACKEND_WORKFLOW_PATH"; then
    SEED_MOUNTED_STATE="1"
  fi

  GO_AHEAD=1
  if [[ "$SEED_MOUNTED_STATE" != "1" ]]; then
    blocker "the SEED_* secrets are still not in $BACKEND_WORKFLOW's --set-secrets."
    say "This deploy will build for 15 minutes and then fail the health gate,"
    say "because seed.py raises before the app can serve /health/ready. See"
    say "Stage 6 for the exact one-line edit."
    printf '\n'
    if (( DRY_RUN )); then
      note "(dry-run) a real run stops here and asks whether to deploy anyway."
      note "Showing the rest of the plan so you can see what it would do."
    elif confirm "flip the gate and deploy anyway, knowing it should fail?"; then
      warn "proceeding at your request."
    else
      GO_AHEAD=0
      say "Not deploying. Make the workflow edit, then re-run:"
      note "    ./deployment/go_live.sh --force-stage BACKEND_DEPLOY"
      SKIPPED+=("first backend deploy (blocked on the SEED_* workflow edit)")
    fi
  fi

  if (( GO_AHEAD )); then
    gh_var DEPLOY_BACKEND_ENABLED "true"
    if (( DRY_RUN )); then
      printf '  %s[dry-run]%s would run: gh workflow run %s --ref main\n' \
        "$YELLOW" "$RESET" "$BACKEND_WORKFLOW"
    else
      run "dispatch $BACKEND_WORKFLOW" gh workflow run "$BACKEND_WORKFLOW" --ref main
      note "waiting 15s for the run to register..."
      nap 15
    fi

    if watch_workflow "$BACKEND_WORKFLOW" "backend deploy" 30; then
      hdr "Resolve the Cloud Run URL"
      BACKEND_URL=$(capture gcloud run services describe "$CLOUD_RUN_SERVICE" \
        --region "$GCP_REGION" --project "$GCP_PROJECT_ID" --format='value(status.url)')
      if [[ -z "$BACKEND_URL" ]]; then
        if (( DRY_RUN )); then
          BACKEND_URL="https://frontshiftai-backend-000000000000.us-central1.run.app"
          note "(dry-run) placeholder backend URL: $BACKEND_URL"
        else
          warn "the deploy reported success but no service URL came back."
          SKIPPED+=("read the Cloud Run URL: gcloud run services describe $CLOUD_RUN_SERVICE --region $GCP_REGION --project $GCP_PROJECT_ID --format='value(status.url)'")
        fi
      else
        ok "backend URL: $BACKEND_URL"
      fi

      if [[ -n "$BACKEND_URL" ]]; then
        record BACKEND_URL "$BACKEND_URL"
        hdr "Independent health check from your machine"
        note "The workflow already gated on this, but a cold start after the"
        note "deploy still takes a while: torch imports plus the MiniLM model"
        note "plus the Chroma collection."
        probe_health "$BACKEND_URL" "/health/ready" 24 || \
          SKIPPED+=("investigate why $BACKEND_URL/health/ready is not 200: gcloud run services logs read $CLOUD_RUN_SERVICE --region $GCP_REGION --project $GCP_PROJECT_ID")
        mark_done BACKEND_DEPLOY
      fi
    else
      warn "the deploy did not succeed, so BACKEND_URL is not being recorded."
      say "Read the logs, fix it, then re-run:"
      note "    ./deployment/go_live.sh --force-stage BACKEND_DEPLOY"
      say "Cloud Run logs, if a revision was created at all:"
      note "    gcloud run services logs read $CLOUD_RUN_SERVICE --region $GCP_REGION --project $GCP_PROJECT_ID --limit 100"
      SKIPPED+=("first backend deploy did not go green")
      (( DRY_RUN )) && mark_done BACKEND_DEPLOY
    fi
  fi
  pause "Continue?"
fi

BACKEND_URL="${BACKEND_URL:-$(state_get BACKEND_URL)}"

# ==========================================================================
# 9. GITHUB PAGES
# ==========================================================================
if begin_stage PAGES_DEPLOY "Point the chat app at the real backend" 6; then

  hdr "Pages configuration"
  PAGES_BUILD_TYPE=$(capture gh api "repos/$GH_REPO_SLUG/pages" --jq '.build_type')
  if [[ "$PAGES_BUILD_TYPE" == "workflow" ]]; then
    ok "Pages is already set to build from a GitHub Actions workflow"
    PAGES_SITE=$(capture gh api "repos/$GH_REPO_SLUG/pages" --jq '.html_url')
    [[ -n "$PAGES_SITE" ]] && note "site: $PAGES_SITE"
  elif [[ -z "$PAGES_BUILD_TYPE" ]]; then
    warn "Pages does not look enabled on this repo."
    say "deploy-pages.yml uses actions/deploy-pages@v4, which needs the source"
    say "set to GitHub Actions."
    maybe_open_url "https://github.com/$GH_REPO_SLUG/settings/pages"
    step "Under Build and deployment, set Source to 'GitHub Actions'."
    pause "Done?"
  else
    warn "Pages build_type is '$PAGES_BUILD_TYPE', not 'workflow'."
    maybe_open_url "https://github.com/$GH_REPO_SLUG/settings/pages"
    step "Change Source to 'GitHub Actions'."
    pause "Done?"
  fi

  hdr "BACKEND_URL"
  if [[ -z "$BACKEND_URL" ]]; then
    warn "no backend URL yet, so the chat app would be built pointing at"
    warn "http://localhost:8000. Finish Stage 8 first."
    SKIPPED+=("set the BACKEND_URL repo variable and re-run $PAGES_WORKFLOW")
  else
    say "This is baked into the bundle at build time as VITE_API_URL, so the"
    say "Pages build has to be re-run whenever it changes."
    gh_var BACKEND_URL "$BACKEND_URL"

    hdr "Build and publish"
    say "Landing page from frontend/ to /FrontShiftAI/"
    say "Chat app from frontend_legacy/ to /FrontShiftAI/app/"
    if (( DRY_RUN )); then
      printf '  %s[dry-run]%s would run: gh workflow run %s --ref main\n' \
        "$YELLOW" "$RESET" "$PAGES_WORKFLOW"
    else
      run "dispatch $PAGES_WORKFLOW" gh workflow run "$PAGES_WORKFLOW" --ref main
      nap 15
    fi
    if watch_workflow "$PAGES_WORKFLOW" "Pages deploy" 15; then
      ok "landing page: $LANDING_URL"
      ok "chat app:     $CHAT_APP_URL"
      mark_done PAGES_DEPLOY
    else
      SKIPPED+=("re-run $PAGES_WORKFLOW; the last run did not go green")
      (( DRY_RUN )) && mark_done PAGES_DEPLOY
    fi
  fi
  pause "Continue?"
fi

# ==========================================================================
# 10. VOICE: LIVEKIT AND PROVIDER KEYS
# ==========================================================================
if begin_stage VOICE_KEYS "LiveKit, voice providers, and the three Modal secrets" 15   ; then

  if ! command -v modal >/dev/null 2>&1; then
    warn "the modal CLI is not installed, so the voice stages cannot run."
    say "    pip install modal && modal token new"
    SKIPPED+=("install the modal CLI, then re-run: ./deployment/go_live.sh --force-stage VOICE_KEYS")
  else
    hdr "Which Modal workspace"
    say "modal secret create and modal deploy both act on your ACTIVE profile."
    say "Deploying into the wrong workspace is silent and confusing, so confirm it."
    if (( DRY_RUN )); then
      note "(dry-run) profiles:"
      capture modal profile list | sed 's/^/    /'
    else
      capture modal profile list | sed 's/^/    /'
    fi
    MODAL_ACTIVE=$(capture modal profile current)
    ok "active profile: ${MODAL_ACTIVE:-unknown}"
    note "The profile name and the workspace name are usually the same, and the"
    note "workspace name is what appears in your Modal web URLs."
    if ! (( NONINTERACTIVE )); then
      if ! confirm "deploy into '$MODAL_ACTIVE'?"; then
        ask_required MODAL_TARGET_PROFILE "Profile to activate:" "$MODAL_ACTIVE"
        must "activate Modal profile $MODAL_TARGET_PROFILE" \
          modal profile activate "$MODAL_TARGET_PROFILE"
        MODAL_ACTIVE="$MODAL_TARGET_PROFILE"
      fi
    fi
    ask_required MODAL_WORKSPACE "Modal workspace name (used to build the URL) [$MODAL_ACTIVE]:" "${MODAL_ACTIVE:-workspace}"
    [[ -n "$MODAL_WORKSPACE" ]] || MODAL_WORKSPACE="$MODAL_ACTIVE"
    record MODAL_WORKSPACE "$MODAL_WORKSPACE"

    # ---- LiveKit ----
    hdr "LiveKit Cloud"
    say "LiveKit carries the audio between the browser and the voice worker."
    maybe_open_url "https://cloud.livekit.io/"
    step "Sign up or log in and create a project."
    step "Open the project, then Settings, then Keys."
    step "Create a key. Copy three things: the project WebSocket URL"
    step "(wss://SOMETHING.livekit.cloud), the API key, and the API secret."
    unverified "LiveKit's console navigation changes; the three values are what"
    unverified "matter, wherever they now live in the UI."
    note "LiveKit Cloud has a free tier with a monthly participant-minute"
    note "allowance. Check the current limits on their pricing page."
    printf '\n'
    ask_required LIVEKIT_URL_VALUE "LIVEKIT_URL (wss://...):" "wss://dry-run.livekit.cloud"
    case "$LIVEKIT_URL_VALUE" in
      wss://*) ok "scheme is wss://" ;;
      ws://*)  warn "ws:// is unencrypted; LiveKit Cloud uses wss://" ;;
      https://*)
        warn "that is the https form. LiveKit clients want wss://."
        if proceed "rewrite https:// to wss:// ?"; then
          LIVEKIT_URL_VALUE="wss://${LIVEKIT_URL_VALUE#https://}"; ok "rewritten"
        fi ;;
      *) warn "that does not look like a LiveKit URL; expected wss://<project>.livekit.cloud" ;;
    esac
    ask_secret_required LIVEKIT_API_KEY_VALUE "LIVEKIT_API_KEY:" "APIdryrun"
    ask_secret_required LIVEKIT_API_SECRET_VALUE "LIVEKIT_API_SECRET:" "secretdryrun"
    record LIVEKIT_URL "$LIVEKIT_URL_VALUE"

    hdr "Creating the $MODAL_SECRET_LIVEKIT Modal secret"
    note "Key names come from voice_pipeline/modal_deploy.py, which reads"
    note "LIVEKIT_URL, LIVEKIT_API_KEY and LIVEKIT_API_SECRET from os.getenv."
    if (( DRY_RUN )); then
      printf '  %s[dry-run]%s would run: modal secret create %s --from-dotenv <0600 temp file> --force\n' \
        "$YELLOW" "$RESET" "$MODAL_SECRET_LIVEKIT"
      note "keys: LIVEKIT_URL, LIVEKIT_API_KEY, LIVEKIT_API_SECRET"
    else
      LK_FILE=$(secret_file "LIVEKIT_URL=$LIVEKIT_URL_VALUE
LIVEKIT_API_KEY=$LIVEKIT_API_KEY_VALUE
LIVEKIT_API_SECRET=$LIVEKIT_API_SECRET_VALUE")
      run "create Modal secret $MODAL_SECRET_LIVEKIT" \
        modal secret create "$MODAL_SECRET_LIVEKIT" --from-dotenv "$LK_FILE" --force
      rm -f "$LK_FILE"
    fi
    unset LIVEKIT_API_KEY_VALUE LIVEKIT_API_SECRET_VALUE

    # ---- providers ----
    hdr "Speech and language providers"
    say "voice_pipeline/configs/default.yaml pins the chain:"
    note "  STT primary   deepgram   nova-2-general"
    note "  STT fallback  assemblyai default"
    note "  LLM primary   openai     gpt-4o-mini"
    note "  TTS primary   deepgram   aura-2-thalia-en"
    note "  TTS fallback  cartesia   sonic-2"
    note "  VAD           silero     (local model, no key)"
    printf '\n'
    warn "Deepgram and OpenAI are the primaries: without them the agent cannot"
    warn "hear, think or speak. AssemblyAI and Cartesia are the configured"
    warn "fallbacks."
    unverified "whether a LiveKit plugin for a fallback raises at construction"
    unverified "time when its key is absent. If it does, a missing AssemblyAI or"
    unverified "Cartesia key breaks worker startup rather than just the fallback."
    unverified "Supply all four if you can, or edit default.yaml to drop the"
    unverified "fallbacks you are not paying for."
    printf '\n'

    maybe_open_url "https://console.deepgram.com/"
    step "Deepgram: log in, then API Keys, then create a key."
    note "Deepgram gives new accounts trial credit; check the current amount."
    ask_secret_required DEEPGRAM_KEY_VALUE "DEEPGRAM_API_KEY:" "dg_dryrun"

    maybe_open_url "https://platform.openai.com/api-keys"
    step "OpenAI: create a secret key (starts with sk-)."
    warn "OpenAI has no free tier. gpt-4o-mini is cheap per token but it is not"
    warn "zero. Set a spend limit in Billing."
    ask_secret_required OPENAI_KEY_VALUE "OPENAI_API_KEY:" "sk-dryrun"

    maybe_open_url "https://www.assemblyai.com/app/api-keys"
    step "AssemblyAI: copy your API key. Enter a placeholder to skip."
    unverified "the AssemblyAI dashboard path."
    ask_secret_required ASSEMBLYAI_KEY_VALUE "ASSEMBLYAI_API_KEY:" "placeholder-not-set"

    maybe_open_url "https://play.cartesia.ai/keys"
    step "Cartesia: create an API key. Enter a placeholder to skip."
    unverified "the Cartesia dashboard path."
    ask_secret_required CARTESIA_KEY_VALUE "CARTESIA_API_KEY:" "placeholder-not-set"

    hdr "Creating the $MODAL_SECRET_PROVIDERS Modal secret"
    note "Key names come from modal_deploy.py's health endpoint, which probes"
    note "OPENAI_API_KEY, DEEPGRAM_API_KEY, CARTESIA_API_KEY, ASSEMBLYAI_API_KEY."
    if (( DRY_RUN )); then
      printf '  %s[dry-run]%s would run: modal secret create %s --from-dotenv <0600 temp file> --force\n' \
        "$YELLOW" "$RESET" "$MODAL_SECRET_PROVIDERS"
      note "keys: OPENAI_API_KEY, DEEPGRAM_API_KEY, ASSEMBLYAI_API_KEY, CARTESIA_API_KEY"
    else
      PROV_FILE=$(secret_file "OPENAI_API_KEY=$OPENAI_KEY_VALUE
DEEPGRAM_API_KEY=$DEEPGRAM_KEY_VALUE
ASSEMBLYAI_API_KEY=$ASSEMBLYAI_KEY_VALUE
CARTESIA_API_KEY=$CARTESIA_KEY_VALUE")
      run "create Modal secret $MODAL_SECRET_PROVIDERS" \
        modal secret create "$MODAL_SECRET_PROVIDERS" --from-dotenv "$PROV_FILE" --force
      rm -f "$PROV_FILE"
    fi
    unset OPENAI_KEY_VALUE DEEPGRAM_KEY_VALUE ASSEMBLYAI_KEY_VALUE CARTESIA_KEY_VALUE

    # ---- backend secret ----
    hdr "The $MODAL_SECRET_BACKEND Modal secret"
    say "voice_pipeline/utils/config.py requires both of these, and raises a"
    say "ValueError at load time if either is missing:"
    note "  VOICE_AGENT_BACKEND_URL  your Cloud Run backend base URL"
    note "  VOICE_AGENT_JWT          a backend-issued JWT, used as a fallback"
    note "                           when a session carries no user token"
    printf '\n'
    if [[ -z "$BACKEND_URL" ]]; then
      warn "no BACKEND_URL yet. Finish Stage 8 first, or paste one now."
      ask_required VOICE_BACKEND_URL "Backend base URL:" "https://frontshiftai-backend-000000000000.us-central1.run.app"
    else
      VOICE_BACKEND_URL="$BACKEND_URL"
      ok "using $VOICE_BACKEND_URL"
    fi

    printf '\n'
    warn "About VOICE_AGENT_JWT: backend/api/auth.py sets"
    warn "ACCESS_TOKEN_EXPIRE_MINUTES = 60, so any token you mint here stops"
    warn "working in an hour. It is genuinely only a fallback: modal_deploy.py's"
    warn "/session endpoint embeds the caller's own JWT in the LiveKit room"
    warn "metadata, and that is what the worker normally uses. A logged-in user"
    warn "clicking the voice button is unaffected by this token expiring. Treat"
    warn "any code path that depends on the fallback as broken after an hour."
    printf '\n'
    say "The old default.yaml hardcoded a super-admin JWT. It is in git history"
    say "and must be treated as compromised, which is why this asks for a fresh"
    say "one against YOUR backend."
    printf '\n'
    VOICE_JWT_VALUE=""
    if [[ -n "$VOICE_BACKEND_URL" ]] && proceed "mint one now by logging in to your backend as the demo user?"; then
      if (( DRY_RUN )); then
        note "(dry-run) would POST $VOICE_BACKEND_URL/api/auth/login and read .access_token"
        VOICE_JWT_VALUE="dry-run-placeholder-jwt"
      else
        DEMO_PW=$(capture gcloud secrets versions access latest --secret=SEED_DEMO_PASSWORD --project "$GCP_PROJECT_ID")
        if [[ -z "$DEMO_PW" ]]; then
          warn "could not read SEED_DEMO_PASSWORD from Secret Manager."
          ask_secret_required DEMO_PW "demo@crousemedical.com password:" ""
        fi
        LOGIN_BODY=$(secret_file "{\"email\":\"demo@crousemedical.com\",\"password\":\"$DEMO_PW\"}")
        VOICE_JWT_VALUE=$(capture curl -s --max-time 60 \
          -X POST "$VOICE_BACKEND_URL/api/auth/login" \
          -H 'Content-Type: application/json' \
          --data-binary "@$LOGIN_BODY" | python3 -c 'import json,sys
try: print(json.load(sys.stdin).get("access_token",""))
except Exception: print("")' )
        rm -f "$LOGIN_BODY"
        unset DEMO_PW
        if [[ -n "$VOICE_JWT_VALUE" ]]; then
          ok "minted an access token (not shown)"
        else
          warn "login failed. The backend may not be seeded yet, or the demo"
          warn "password may not match. Paste a token by hand instead."
        fi
      fi
    fi
    if [[ -z "$VOICE_JWT_VALUE" ]]; then
      say "Get one by hand:"
      note "  curl -s -X POST $VOICE_BACKEND_URL/api/auth/login \\"
      note "    -H 'Content-Type: application/json' \\"
      note "    -d '{\"email\":\"demo@crousemedical.com\",\"password\":\"...\"}'"
      note "and copy the access_token field."
      ask_secret_required VOICE_JWT_VALUE "VOICE_AGENT_JWT:" "dry-run-placeholder-jwt"
    fi

    if (( DRY_RUN )); then
      printf '  %s[dry-run]%s would run: modal secret create %s --from-dotenv <0600 temp file> --force\n' \
        "$YELLOW" "$RESET" "$MODAL_SECRET_BACKEND"
      note "keys: VOICE_AGENT_BACKEND_URL, VOICE_AGENT_JWT"
    else
      BE_FILE=$(secret_file "VOICE_AGENT_BACKEND_URL=$VOICE_BACKEND_URL
VOICE_AGENT_JWT=$VOICE_JWT_VALUE")
      run "create Modal secret $MODAL_SECRET_BACKEND" \
        modal secret create "$MODAL_SECRET_BACKEND" --from-dotenv "$BE_FILE" --force
      rm -f "$BE_FILE"
    fi
    unset VOICE_JWT_VALUE

    hdr "Optional: wandb-credentials"
    say "modal_deploy.py tries modal.Secret.from_name('wandb-credentials') and"
    say "logs an ERROR if it is absent. The deploy still works; voice metrics"
    say "fall back to a metrics.jsonl file in the container's /tmp."
    if proceed "add a W&B key?"; then
      maybe_open_url "https://wandb.ai/authorize"
      ask_secret_required WANDB_KEY_VALUE "WANDB_API_KEY:" "placeholder-not-set"
      if (( DRY_RUN )); then
        printf '  %s[dry-run]%s would run: modal secret create wandb-credentials --from-dotenv <0600 temp file> --force\n' "$YELLOW" "$RESET"
      else
        WB_FILE=$(secret_file "WANDB_API_KEY=$WANDB_KEY_VALUE")
        run "create Modal secret wandb-credentials" \
          modal secret create wandb-credentials --from-dotenv "$WB_FILE" --force
        rm -f "$WB_FILE"
      fi
      unset WANDB_KEY_VALUE
    else
      note "skipping. Expect one ERROR line in the Modal deploy output."
    fi

    mark_done VOICE_KEYS
  fi
  pause "Continue?"
fi

MODAL_WORKSPACE="${MODAL_WORKSPACE:-$(state_get MODAL_WORKSPACE)}"

# ==========================================================================
# 11. MODAL DEPLOY
# ==========================================================================
if begin_stage MODAL_DEPLOY "Deploy the voice agent and wire VOICE_API_URL" 10; then

  if ! command -v modal >/dev/null 2>&1; then
    warn "the modal CLI is missing; skipping."
    SKIPPED+=("deploy the voice agent: modal deploy voice_pipeline/modal_deploy.py")
  else
    hdr "Deploy"
    note "This builds a debian_slim image with the livekit-agents extras and"
    note "copies voice_pipeline/ into it. First build takes a few minutes."
    note "Run from the repo root so the relative path resolves."
    if (( DRY_RUN )); then
      printf '  %s[dry-run]%s would run: (cd %q && modal deploy voice_pipeline/modal_deploy.py)\n' \
        "$YELLOW" "$RESET" "$REPO_ROOT"
    else
      say "Output follows. Copy the web_api URL it prints."
      printf '\n'
      if ( cd "$REPO_ROOT" && modal deploy voice_pipeline/modal_deploy.py ); then
        ok "modal deploy finished"
      else
        warn "modal deploy failed. Common causes: a missing Modal secret (all"
        warn "three of $MODAL_SECRET_LIVEKIT, $MODAL_SECRET_PROVIDERS and"
        warn "$MODAL_SECRET_BACKEND must exist), or the wrong active workspace."
        SKIPPED+=("modal deploy voice_pipeline/modal_deploy.py")
      fi
    fi

    hdr "The web endpoint URL"
    MODAL_URL_GUESS="https://${MODAL_WORKSPACE:-workspace}--$MODAL_APP-web-api.modal.run"
    say "Modal derives it from your workspace, the app name and the function"
    say "name, so it is usually:"
    note "  $MODAL_URL_GUESS"
    warn "Do not trust that guess. Use the URL modal printed above."
    unverified "Modal's URL scheme has changed before, and a workspace whose name"
    unverified "differs from the profile name breaks the guess."
    ask_required VOICE_API_URL_VALUE "Voice API URL:" "$MODAL_URL_GUESS"
    case "$VOICE_API_URL_VALUE" in
      https://*) ok "scheme is https://" ;;
      *) warn "expected an https:// URL" ;;
    esac
    VOICE_API_URL_VALUE="${VOICE_API_URL_VALUE%/}"

    hdr "Check it answers"
    if probe_health "$VOICE_API_URL_VALUE" "/health" 6; then
      if ! (( DRY_RUN )); then
        say "What /health reports (livekit_configured and the provider flags"
        say "should all be true for anything you supplied a real key for):"
        capture curl -s --max-time 20 "$VOICE_API_URL_VALUE/health" | sed 's/^/    /'
      fi
    else
      SKIPPED+=("check $VOICE_API_URL_VALUE/health; the first request is a cold start, try again")
    fi

    record VOICE_API_URL "$VOICE_API_URL_VALUE"
    gh_var VOICE_API_URL "$VOICE_API_URL_VALUE"

    hdr "Rebuild Pages so the chat app knows the voice URL"
    say "VOICE_API_URL is baked in at build time as VITE_VOICE_API_URL, so"
    say "setting the variable changes nothing until Pages is rebuilt."
    if (( DRY_RUN )); then
      printf '  %s[dry-run]%s would run: gh workflow run %s --ref main\n' \
        "$YELLOW" "$RESET" "$PAGES_WORKFLOW"
    else
      run "dispatch $PAGES_WORKFLOW" gh workflow run "$PAGES_WORKFLOW" --ref main
      nap 15
    fi
    watch_workflow "$PAGES_WORKFLOW" "Pages rebuild" 15 || \
      SKIPPED+=("re-run $PAGES_WORKFLOW so the chat app picks up VOICE_API_URL")

    mark_done MODAL_DEPLOY
  fi
  pause "Continue?"
fi

VOICE_API_URL_VALUE="${VOICE_API_URL_VALUE:-$(state_get VOICE_API_URL)}"

# ==========================================================================
# 12. FINAL VERIFICATION
# ==========================================================================
if begin_stage VERIFY "Verify it end to end" 6; then

  hdr "Your URLs"
  say "Landing page   $LANDING_URL"
  say "Chat app       $CHAT_APP_URL"
  say "Backend        ${BACKEND_URL:-NOT DEPLOYED}"
  say "Voice API      ${VOICE_API_URL_VALUE:-NOT DEPLOYED}"
  printf '\n'

  hdr "Automated checks"
  if [[ -n "$BACKEND_URL" ]]; then
    probe_health "$BACKEND_URL" "/health" 3 || true
    probe_health "$BACKEND_URL" "/health/ready" 3 || true
  else
    warn "no backend URL to check"
  fi
  if [[ -n "$VOICE_API_URL_VALUE" ]]; then
    probe_health "$VOICE_API_URL_VALUE" "/health" 3 || true
  else
    warn "no voice URL to check"
  fi
  if [[ -n "$BACKEND_URL" && -n "$VOICE_API_URL_VALUE" ]] && ! (( DRY_RUN )); then
    say "Deep voice check (does Modal reach LiveKit and your backend?):"
    capture curl -s --max-time 30 "$VOICE_API_URL_VALUE/health/deep" | sed 's/^/    /'
  fi

  hdr "Now click through it yourself"
  step "1. Open $LANDING_URL. The landing page should render with no console errors."
  step "2. Open $CHAT_APP_URL and check the Network tab: requests must go to"
  step "   ${BACKEND_URL:-your Cloud Run URL}, NOT localhost:8000. If you see"
  step "   localhost, BACKEND_URL was unset when Pages was built. Set it and"
  step "   re-run $PAGES_WORKFLOW."
  step "3. Log in as demo@crousemedical.com with SEED_DEMO_PASSWORD:"
  note "      gcloud secrets versions access latest --secret=SEED_DEMO_PASSWORD --project $GCP_PROJECT_ID"
  step "4. Ask a handbook question, for example 'how much PTO do I get?'. An"
  step "   answer with citations means Chroma, the embedding model and the"
  step "   Mercury generation path are all alive."
  step "5. File a PTO request. That proves Neon is writable, not just readable."
  step "6. Confirm tenant isolation: as the demo user you must not be able to"
  step "   see another company's data or any admin view."
  step "7. Click the voice button and say something. First use is a cold start,"
  step "   roughly 5 to 15 seconds before the agent speaks."
  step "8. Come back after 20 minutes of no traffic, so min-instances 0 has let"
  step "   the container die, and log in again. Your account and your PTO request"
  step "   must still be there. That is the real proof the database is durable:"
  step "   on the old SQLite-on-Cloud-Run setup both would have vanished."
  printf '\n'

  hdr "Set a budget alert before you walk away"
  maybe_open_url "https://console.cloud.google.com/billing"
  step "Billing, then Budgets and alerts, then create a budget with an email"
  step "threshold. A runaway loop against an LLM API is the expensive failure"
  step "mode here, not Cloud Run."
  printf '\n'

  hdr "Useful afterwards"
  note "backend logs   gcloud run services logs read $CLOUD_RUN_SERVICE --region $GCP_REGION --project $GCP_PROJECT_ID --limit 100"
  note "voice logs     modal app logs $MODAL_APP"
  note "deploy runs    gh run list --workflow $BACKEND_WORKFLOW"
  note "turn deploys off again  gh variable set DEPLOY_BACKEND_ENABLED --body false"
  note "wizard state   ./deployment/go_live.sh --status"
  printf '\n'
  mark_done VERIFY
  pause "Done?"
fi

# ==========================================================================
finish

if (( ${#RESUMED[@]} )); then
  note "skipped as already complete: ${RESUMED[*]}"
  printf '\n'
fi

if (( ${#BLOCKERS[@]} )); then
  printf '  %s%sBlockers raised this run%s\n' "$BOLD" "$RED" "$RESET"
  for b in "${BLOCKERS[@]}"; do note "  - $b"; done
  printf '\n'
fi

printf '  %sURLs%s\n' "$BOLD" "$RESET"
note "  landing   $LANDING_URL"
note "  chat app  $CHAT_APP_URL"
note "  backend   ${BACKEND_URL:-not deployed}"
note "  voice     ${VOICE_API_URL_VALUE:-not deployed}"
printf '\n'
note "Re-run any time: ./deployment/go_live.sh"
note "See what is recorded: ./deployment/go_live.sh --status"
note "Read the companion doc: deployment/GO_LIVE.md"
printf '\n'
(( DRY_RUN )) && warn "That was a DRY RUN. Nothing was created or changed."
printf '\n'
